name: Init-CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
      

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.18', '1.19', '>=1.19']
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
        
      - name: Build-DB
        run: docker-compose build
        
      - name: Create_DB
        run: docker-compose up -d
        
      - name: Test
        run: go test -v main_test.go

  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.19', '>=1.19']
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: go build -v main.go

        
