go# This is a basic workflow to help you get started with Actions

name: Init-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
    matrix:
      go_version: ['1.17', '1.18', '>=1.18']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
        go_version: ${{ matrix.go_version }}
        
      - name: Build-DB
        run: docker-compose build
        
      - name: Create_DB
        run: docker-compose up -v
        
      - name: Test
        run: go test -v main_test.go
        
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Build
        run: go build -v main.go
        
        
